### PR TITLE
Readme: Add discord server link

### PR DESCRIPTION
**Pull request by bbbbbr**
Wasn't sure whether or not to mention ZGB in there.

### CODE REVIEW

**Comment by Zal0** [comment]
Hmmm
Have we removed the link to gbdev? I think both links should  appear

**Comment by untoxa** [comment]
no, nothing is removed by that commit.

**Comment by Zal0** [comment]
Ok... Right now it's a bot confusing because that link is up there but there is a link to the other server in the docs section

**Comment by bbbbbr** [comment]
I'll submit another PR that brings both sections together. Same for the docs, since those have two entries as well.

**Comment by bbbbbr** [comment]
Fixes in #112

**Pull request merged**
