### PR TITLE
interrupts fix

### PR DESCRIPTION
**Pull request by untoxa**
functions were perfect, except
`LDA	HL,4(SP)	; Skip return address and registers`
and
`LDA	HL,.BANKOV+2(SP); Skip return address and registers`

### CODE REVIEW

**Comment by untoxa** [comment]
fixed multiple exceptions when run in "rom cart troubleshooting mode"

**Comment by untoxa** [comment]
change the interrupt handler default behaviour

**Comment by untoxa** [comment]
there is a well-known bug in DMG hardware: https://gbdev.io/pandocs/#sprite-ram-bug
we have also a bug in crt0 code, that encounters this hardware bug, that results in filling the OAM with random data on startup instead of cleanup. and the other problem - when you run your rom in"troubleshooting mode" of a BGB emu, you always receive 256 exceptions while still in initialization stub. this patch fixes both problems: OAM is cleared and no exceptions in BGB while troubleshooting the rom.

**Comment by untoxa** [comment]
__BGB_PROFILER_INIT must be static

**Comment by untoxa** [comment]
BGB_MESSAGE_FMT macro allows to output formatted strings

**Comment by Zal0** [comment]
> 
> 
> there is a well-known bug in DMG hardware: https://gbdev.io/pandocs/#sprite-ram-bug
> we have also a bug in crt0 code, that encounters this hardware bug, that results in filling the OAM with random data on startup instead of OAM cleanup. and the other problem - when you run your rom in"troubleshooting mode" of a BGB emu, you always receive 256 exceptions while still in initialization stub. this patch fixes both problems: OAM is cleared and no exceptions in BGB while troubleshooting the rom.

I am still getting those 255 warnings, did you test this LOL?

**Comment by Zal0** [comment]
All changes merged

**Pull request closed without merging**
