### PR TITLE
Optimize cgb.s

### PR DESCRIPTION
**Pull request by ISSOtm**
Uniformize palette routines (using `ldh [c], a`) to save space at the cost of a handful of cycles, sometimes saving some
Optimize various routines at ASM level and by using palette index auto-increment, saving one register pair (+ 7 cycles)
Increase VRAM access tolerance

### CODE REVIEW

**Comment by Zal0** [comment]
The new code doesn't work 
Take a look at the screenshots
https://drive.google.com/file/d/1faedxPpM0KgNM6TjgFx1dA3UUJPNEIWq/view?usp=sharing, https://drive.google.com/file/d/1o9e7viJwR1KBC1hEk95zavF0M6rU2V3I/view?usp=sharing

This is how they should look
https://drive.google.com/file/d/16_GLDuExfrOad9edyJGYysjOkXwpLd3w/view?usp=sharing, https://drive.google.com/file/d/1C4dEFxr1YAtaTQS98HnWVHq2YrH8kEj2/view?usp=sharing, 

Please test the code before commiting it

**Comment by Zal0** [comment]
This was fixed by Toxa and it's merged now

**Comment by ISSOtm** [comment]
Where was it fixed? The [history](https://github.com/Zal0/gbdk-2020/commits/11a44c3cad913f0bacf77257199fa0bc0c10541b/gbdk-lib/libc/gb/cgb.s) notes no modification besides the original commit.

If the code is broken, I cannot fix it by looking at such screenshots. I'd need to look at data—loaded palettes in the VRAM viewer, if anything? Best would be a ROM and code to debug, though.

As I explained in chat, I cannot test GBDK code because I have neither the tools, nor code to test with. I reviewed my code in parallel with the original, and tried to keep identical functionality. I though this would be enough.

**Comment by Zal0** [comment]
It was fixed [here](https://github.com/Zal0/gbdk-2020/commit/a134165fc6c81971f998d1154441b62bbc3b4a82)

I appreciate your efforts a lot but I hope you understand that we need code that is tested and working

**Pull request closed without merging**
