### PR TITLE
Add multiple write check for IHX files (ihxcheck) to build process

### PR DESCRIPTION
**Pull request by bbbbbr**
* Add ihx multiple write tool "ihxcheck" tool to gbdk-support
* Build ihxcheck with main Makefile
* Call ihxcheck from Lcc after ihx file has been generated with linker
* Allow passing an argument to ihxcheck via lcc (-Wi-e) to error out instead of just warn on multiple writes

### CODE REVIEW

**Comment by bbbbbr** [comment]
BTW, this is a candidate for #72

**Comment by untoxa** [comment]
need a simple way to switch this tool off with a commandline argument

**Comment by bbbbbr** [comment]
That could be either a primary Lcc switch or a pass-through switch to ihxcheck which causes it to not process and exit immediately. Any preference?

**Comment by untoxa** [comment]
LCC switch

**Comment by bbbbbr** [comment]
Switch name is easy to change if K isn't desired.

**Pull request merged**
