### PR TITLE
Unify bin directories and improve lcc

### PR DESCRIPTION
**Pull request by basxto**
- merge `bin` and `bin/SDCC/bin`
- support `//`, `/./`, `/../` with `lcc`
- add `--sdccbin=` to lcc

### CODE REVIEW

**Comment by Zal0** [comment]
Why do you want to unify sdcc/bin into bin?
Updating SDCC it's easier if it's on a separate folder

**Comment by basxto** [comment]
1. `bin` directories are unified so it is compatible with UNIX file structure `${prefix}/bin` `${prefix}/lib`, which can be `/bin`, `/usr/bin` etc.
2. Fixes #29
3. `--sdccbin=` is for the case sdcc and gdbk are in different folders, which happens when you build your own portable gbdk and use installed sdcc or if one wants to use it with a newer sdcc version in case it dies like original gbdk.

With just 3. it would be neccessary to write a wrapper script when you want to put lcc in `/usr/bin`. Without 1. and 3. it would be neccessary to write a wrapper script and to create symbolic links to all sdcc executables.

Why is it simpler, don’t you just overwrite the files?

**Comment by Zal0** [comment]
Thanks a lot. I'll test it on Windows and MacOS and merge it
Does this fix Linux packaging issues?

**Comment by basxto** [comment]
Nearly, I still have to modify `bindir` in `gb.c`.
And it looks like `--help` is broken, but that was already the case in `v3.2`.

**Comment by basxto** [comment]
I wrote an  arch linux package based on that.

**Comment by basxto** [comment]
With that update it can now be built without manipulating any files.

**Comment by basxto** [comment]
Windows should use the old directory again.
I hope it’s mergable this way.

**Comment by untoxa** [comment]
fixed other way in v4.0 release

**Pull request closed without merging**
