### PR TITLE
LCD interrupt must NOT wait for the compatible LCD mode

### PR DESCRIPTION
**Pull request by untoxa**
LCD interrupt must NOT wait for the compatible LCD mode, because that excludes the possibility of making effects, that require every HBlank interrupt. wobble.c is an example of such an effect written in pure C. Compile wobble.c with and without a patch to see the difference.

### CODE REVIEW

**Comment by untoxa** [comment]
nowait_int_handler() does not help here, because the resulting construction too slow for an HBlank, which must be less than 114 cycles.

**Comment by Zal0** [comment]
so... should we merge any of this?

**Comment by untoxa** [comment]
yes, that's why we need to change the default behaviour for an LCD handler (only that handler). to make possible some minimal reasonable interrupt. i think that interrupt handler chain for LCD interrupt is useless, maybe we must make only one interrupt handler for LCD possible ( but leaving the compatible API: add_LCD(), remove_LCD() ) - that saves the cycles and allows to write a bit more complex handlers within that very short time intervals? iterating through the vector "eats" too much.

**Comment by untoxa** [comment]
I moved the LCD interrupt handler out of crt0. The changes are compatible and transparent.

**Comment by untoxa** [comment]
".globl    .add_LCD" must be commented out, since we can have custom hardcoded handlers now.

**Comment by Zal0** [comment]
This has been merged to develop now

**Pull request closed without merging**
