### PR TITLE
BANKED/NONBANKED defines fixed

### PR DESCRIPTION
**Pull request by untoxa**

### CODE REVIEW

**Comment by untoxa** [comment]
library workaround fix

**Comment by untoxa** [comment]
--profile switch support

**Comment by untoxa** [comment]
Zal0, it points to incorrect bank and must be fixed. Let it point to the correct bank and also be fixed. :)

**Comment by Zal0** [comment]
> 
> 
> Zal0, it points to incorrect bank and must be fixed. Let it point to the correct bank and also be fixed. :)

OK, changed... but isn't it weird that it was pointing to bank 1 for some unknown reason?

**Comment by untoxa** [comment]
they wanted a banked main() at some point.

**Comment by Zal0** [comment]
All changes are now merged in develop branch

**Pull request closed without merging**
